#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2021 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "onedark"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    default_indent=4
    default_shell="terminal"
    filetree_direction = "left"
    


# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 25

[[layers]]
name = 'colorscheme'

[[layers]]
name = "default"

[[layers]]
name = "fzf"

[[layers]]
  name = 'lang#rust'
  format_on_save = true
  rustfmt_cmd = "/home/xdrag/.cargo/bin/rustfmt"

[[layers]]
  name = "lang#toml"

[[layers]]
  name = "lsp"
  filetypes = [
    "rust",
    "go",
    "python",
    "sh",
    "vim"
    "javascript",
    "typescript"
  ]
  [layers.override_cmd]
    rust = ["rls"]

[[layers]]
  name = "lang#c"
  enable_clang_syntax_highlight = true
  format_on_save = false
  clang_flag=['-I/opt/intel/sgxsdk/include']
  [layer.clang_std]
    cpp = "c17"

[[layers]]
  name = "lang#go"
  enabled_linters = ["golangci_lint", "govet"]
  format_on_save = true

[[layers]]
  name = "lang#dockerfile"
  format_on_save = true

[[layers]]
  name = "lang#vim"

[[layers]]
  name = "lang#markdown"
  format_on_save = true

[[layers]]
  name = "lang#sh"
  format_on_save = true

[[layers]]
  name = "lang#latex"

[[layers]]
  name = "lang#python"
  format_on_save = true
  python_file_head = [
    '#!/usr/bin/env python3',
    '# -*- coding: utf-8 -*-',
    '',
    ''
  ]
  python_interpreter = "/usr/bin/python3"
  enabled_linters = ['python', 'pylint']

[[layers]]
  name = "denite"

[[layers]]
  name = "checkers"

[[layers]]
  name = "format"

[[layers]]
  name = "cscope"

[[layers]]
  name = "ctrlspace"

[[custom_plugins]]
  name = 'wakatime/vim-wakatime'

[[custom_plugins]]
  name = 'fatih/vim-go'
